# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert vector to factor
#' @param x : vector
#' @export
fast_factor <- function(x) {
    .Call('RcppUtil_fast_factor', PACKAGE = 'RcppUtil', x)
}

#' @useDynLib RcppUtil
#' @importFrom Rcpp evalCpp
NULL

#' Create sparse matrix from data.frame
#' @param df : data.frame
#' @param checkNA : set false if you can gualantee there is no NAs in the df.
#' @export
asSparseMatrix <- function(df, checkNA = TRUE) {
    .Call('RcppUtil_asSparseMatrix', PACKAGE = 'RcppUtil', df, checkNA)
}

#' @export
sparseMatrixToDataFrame <- function(sm) {
    .Call('RcppUtil_sparseMatrixToDataFrame', PACKAGE = 'RcppUtil', sm)
}

catdap <- function(y, x) {
    .Call('RcppUtil_catdap', PACKAGE = 'RcppUtil', y, x)
}

#' apply_catdap
#' @param y : vector
#' @param df : data.frame
#' @export
apply_catdap <- function(y, df) {
    .Call('RcppUtil_apply_catdap', PACKAGE = 'RcppUtil', y, df)
}

#' apply funciton to data.frame column
#'
#' @param df : data.frame
#' @param n : number of cores for parallel operation
#' @export
thread_function <- function(df, n) {
    .Call('RcppUtil_thread_function', PACKAGE = 'RcppUtil', df, n)
}

#' apply funciton to data.frame column
#'
#' @param df : data.frame
#' @param n : number of cores for parallel operation
#' @export
thread_function2 <- function(df, n) {
    .Call('RcppUtil_thread_function2', PACKAGE = 'RcppUtil', df, n)
}

#' apply funciton to data.frame column
#'
#' @param df : data.frame
#' @param n : number of cores for parallel operation
#' @export
thread_function3 <- function(df, n) {
    .Call('RcppUtil_thread_function3', PACKAGE = 'RcppUtil', df, n)
}

makeDummyList <- function(x, fullrank = TRUE, prefix = "") {
    .Call('RcppUtil_makeDummyList', PACKAGE = 'RcppUtil', x, fullrank, prefix)
}

makeDummyDf <- function(x, fullrank = TRUE, prefix = "") {
    .Call('RcppUtil_makeDummyDf', PACKAGE = 'RcppUtil', x, fullrank, prefix)
}

make_dummy_p <- function(df, cores = 2L, sep_cat = "_", fullrank = TRUE) {
    .Call('RcppUtil_make_dummy_p', PACKAGE = 'RcppUtil', df, cores, sep_cat, fullrank)
}

make_dummy_pp <- function(df, cores = 2L, sep_cat = "_", fullrank = TRUE) {
    .Call('RcppUtil_make_dummy_pp', PACKAGE = 'RcppUtil', df, cores, sep_cat, fullrank)
}

